authors:
  antwanchild:
    name: Anthony Child
    description: Blogger, Homelab creator
    avatar: https://github.com/antwanchild.png
  krissie:
    name: Krissie Child
    description: She's a little Red...
    avatar: https://ui-avatars.com/api/?name=Krissie+Child&background=random
